# Generated by Django 5.0.1 on 2024-01-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.CharField(max_length=50)),
                ('period2', models.CharField(max_length=50)),
                ('period3', models.CharField(max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.CharField(max_length=50)),
                ('period2', models.CharField(max_length=50)),
                ('period3', models.CharField(max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.CharField(max_length=50)),
                ('period2', models.CharField(max_length=50)),
                ('period3', models.CharField(max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.CharField(max_length=50)),
                ('period2', models.CharField(max_length=50)),
                ('period3', models.CharField(max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
